<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Learning.GraduationProject.Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\Auth\**" />
    <EmbeddedResource Remove="Services\Auth\**" />
    <None Remove="Services\Auth\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Learning.GraduationProject.Repository\E-Learning.GraduationProject.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
  </ItemGroup>

</Project>
